repos:
    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
            args: [
                    "-rn", # Only display messages
                    "-sn", # Don't display the score
                ]
            stages: [commit]
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
          - id: black
            stages: [commit]
    - repo: local
      hooks:
          - id: flake8
            name: flake8
            entry: flake8
            language: system
            types: [python]
            stages: [commit]
    # - repo: local
    #   hooks:
    #       - id: pytest-check
    #         name: pytest-check
    #         entry: pytest
    #         language: system
    #         pass_filenames: false
    #         always_run: true
    #         stages: [push]